/*
 * This file is part of rawform.
 * Copyright (C) 2026 Etienne Fleurant
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// SearchPresetStore.cpp
//
// The Find binding of NamedPatternStore: file name and banner only.

#include "search/SearchPresetStore.h"

#include <QByteArray>
#include <QLatin1String>
#include <QString>

namespace rawform {
namespace {

/// Filename of the app-managed Find-presets file (under userConfigDir()).
constexpr auto kSearchFiltersFileName = "search_filters.yaml";

/// The comment block written above the emitted YAML.
constexpr auto kSearchFiltersBanner =
    "# rawform - saved Find filters (generated by the app).\n"
    "# Each entry: a preset name and a Filter-box expression: entries\n"
    "# separated by ':', each a column title, a custom column's name, a\n"
    "# field id, or a %token% pattern (e.g. Artist:Album:%composer%).\n"
    "# Delete an entry (or the whole file) to remove a preset.\n";

} // namespace

SearchPresetStore::SearchPresetStore(QObject* parent)
    : NamedPatternStore(QLatin1String(kSearchFiltersFileName),
                        QByteArray(kSearchFiltersBanner),
                        QStringLiteral("Find presets"), parent) {}

} // namespace rawform
